apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: devops-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata: 
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/nikolayzdravkov/devops-site-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: postgres_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db_password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: postgres_db
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"

